apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spanner-ns
  name: irahul-multi-ro-query-classic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: irahul-multi-ro-query-classic
  template:
    metadata:
      labels:
        app: irahul-multi-ro-query-classic
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: multi-ro-query
          image: us-west1-docker.pkg.dev/outbound-flight/spanner-box/irahul-client:latest
          command: ["java"]
          args:
            - -XX:-TieredCompilation
            - -XX:CompileThreshold=1000
            - -jar
            - /app/main.jar
          resources:
            requests:
              memory: "400Mi"
              cpu: "0.4"
            limits:
              memory: "400Mi"
              cpu: "0.4"
          env:
            - name: PROBE_TYPE
              value: "multi_use_ro_query"
            - name: QPS
              value: "10"
            - name: ENDPOINT
              value: "http://10.142.15.195:15000"
            - name: OTEL_SERVICE_NAME
              value: "irahul-jbypass-multi-ro-classic"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spanner-ns
  name: irahul-multi-ro-query-bypass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: irahul-multi-ro-query-bypass
  template:
    metadata:
      labels:
        app: irahul-multi-ro-query-bypass
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: multi-ro-query
          image: us-west1-docker.pkg.dev/outbound-flight/spanner-box/irahul-client:latest
          command: ["java"]
          args:
            - -XX:-TieredCompilation
            - -XX:CompileThreshold=1000
            - -jar
            - /app/main.jar
          resources:
            requests:
              memory: "400Mi"
              cpu: "0.4"
            limits:
              memory: "400Mi"
              cpu: "0.4"
          env:
            - name: PROBE_TYPE
              value: "multi_use_ro_query"
            - name: GOOGLE_SPANNER_EXPERIMENTAL_LOCATION_API
              value: "true"
            - name: QPS
              value: "10"
            - name: ENDPOINT
              value: "http://10.142.15.195:15000"
            - name: OTEL_SERVICE_NAME
              value: "irahul-jbypass-multi-ro-bypass"
