/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/admin/instance/v1/spanner_instance_admin.proto

package com.google.spanner.admin.instance.v1;

public final class SpannerInstanceAdminProto {
  private SpannerInstanceAdminProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_ReplicaInfo_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_ReplicaInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_InstanceConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_InstanceConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_InstanceConfig_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_InstanceConfig_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_AutoscalingLimits_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_AutoscalingLimits_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_AutoscalingTargets_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_AutoscalingTargets_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_Instance_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_Instance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_Instance_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_Instance_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_ListInstanceConfigsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_ListInstanceConfigsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_ListInstanceConfigsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_ListInstanceConfigsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_GetInstanceConfigRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_GetInstanceConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_CreateInstanceConfigRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_CreateInstanceConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_UpdateInstanceConfigRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_UpdateInstanceConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_DeleteInstanceConfigRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_DeleteInstanceConfigRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_ListInstanceConfigOperationsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_ListInstanceConfigOperationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_ListInstanceConfigOperationsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_ListInstanceConfigOperationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_GetInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_GetInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_CreateInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_CreateInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_ListInstancesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_ListInstancesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_ListInstancesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_ListInstancesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_UpdateInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_UpdateInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_DeleteInstanceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_DeleteInstanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_CreateInstanceMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_CreateInstanceMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_UpdateInstanceMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_UpdateInstanceMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_CreateInstanceConfigMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_CreateInstanceConfigMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_spanner_admin_instance_v1_UpdateInstanceConfigMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_spanner_admin_instance_v1_UpdateInstanceConfigMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n=google/spanner/admin/instance/v1/spann"
          + "er_instance_admin.proto\022 google.spanner."
          + "admin.instance.v1\032\034google/api/annotation"
          + "s.proto\032\027google/api/client.proto\032\037google"
          + "/api/field_behavior.proto\032\031google/api/re"
          + "source.proto\032\036google/iam/v1/iam_policy.p"
          + "roto\032\032google/iam/v1/policy.proto\032#google"
          + "/longrunning/operations.proto\032\033google/pr"
          + "otobuf/empty.proto\032 google/protobuf/fiel"
          + "d_mask.proto\032\037google/protobuf/timestamp."
          + "proto\032-google/spanner/admin/instance/v1/"
          + "common.proto\"\332\001\n\013ReplicaInfo\022\020\n\010location"
          + "\030\001 \001(\t\022G\n\004type\030\002 \001(\01629.google.spanner.ad"
          + "min.instance.v1.ReplicaInfo.ReplicaType\022"
          + "\037\n\027default_leader_location\030\003 \001(\010\"O\n\013Repl"
          + "icaType\022\024\n\020TYPE_UNSPECIFIED\020\000\022\016\n\nREAD_WR"
          + "ITE\020\001\022\r\n\tREAD_ONLY\020\002\022\013\n\007WITNESS\020\003\"\302\006\n\016In"
          + "stanceConfig\022\014\n\004name\030\001 \001(\t\022\024\n\014display_na"
          + "me\030\002 \001(\t\022P\n\013config_type\030\005 \001(\01625.google.s"
          + "panner.admin.instance.v1.InstanceConfig."
          + "TypeB\004\342A\001\003\022?\n\010replicas\030\003 \003(\0132-.google.sp"
          + "anner.admin.instance.v1.ReplicaInfo\022N\n\021o"
          + "ptional_replicas\030\006 \003(\0132-.google.spanner."
          + "admin.instance.v1.ReplicaInfoB\004\342A\001\003\022?\n\013b"
          + "ase_config\030\007 \001(\tB*\372A\'\n%spanner.googleapi"
          + "s.com/InstanceConfig\022L\n\006labels\030\010 \003(\0132<.g"
          + "oogle.spanner.admin.instance.v1.Instance"
          + "Config.LabelsEntry\022\014\n\004etag\030\t \001(\t\022\026\n\016lead"
          + "er_options\030\004 \003(\t\022\031\n\013reconciling\030\n \001(\010B\004\342"
          + "A\001\003\022K\n\005state\030\013 \001(\01626.google.spanner.admi"
          + "n.instance.v1.InstanceConfig.StateB\004\342A\001\003"
          + "\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 "
          + "\001(\t:\0028\001\"B\n\004Type\022\024\n\020TYPE_UNSPECIFIED\020\000\022\022\n"
          + "\016GOOGLE_MANAGED\020\001\022\020\n\014USER_MANAGED\020\002\"7\n\005S"
          + "tate\022\025\n\021STATE_UNSPECIFIED\020\000\022\014\n\010CREATING\020"
          + "\001\022\t\n\005READY\020\002:`\352A]\n%spanner.googleapis.co"
          + "m/InstanceConfig\0224projects/{project}/ins"
          + "tanceConfigs/{instance_config}\"\337\003\n\021Autos"
          + "calingConfig\022a\n\022autoscaling_limits\030\001 \001(\013"
          + "2E.google.spanner.admin.instance.v1.Auto"
          + "scalingConfig.AutoscalingLimits\022c\n\023autos"
          + "caling_targets\030\002 \001(\0132F.google.spanner.ad"
          + "min.instance.v1.AutoscalingConfig.Autosc"
          + "alingTargets\032\227\001\n\021AutoscalingLimits\022\023\n\tmi"
          + "n_nodes\030\001 \001(\005H\000\022\036\n\024min_processing_units\030"
          + "\002 \001(\005H\000\022\023\n\tmax_nodes\030\003 \001(\005H\001\022\036\n\024max_proc"
          + "essing_units\030\004 \001(\005H\001B\013\n\tmin_limitB\013\n\tmax"
          + "_limit\032h\n\022AutoscalingTargets\022-\n%high_pri"
          + "ority_cpu_utilization_percent\030\001 \001(\005\022#\n\033s"
          + "torage_utilization_percent\030\002 \001(\005\"\304\005\n\010Ins"
          + "tance\022\022\n\004name\030\001 \001(\tB\004\342A\001\002\022>\n\006config\030\002 \001("
          + "\tB.\342A\001\002\372A\'\n%spanner.googleapis.com/Insta"
          + "nceConfig\022\032\n\014display_name\030\003 \001(\tB\004\342A\001\002\022\022\n"
          + "\nnode_count\030\005 \001(\005\022\030\n\020processing_units\030\t "
          + "\001(\005\022E\n\005state\030\006 \001(\01620.google.spanner.admi"
          + "n.instance.v1.Instance.StateB\004\342A\001\003\022F\n\006la"
          + "bels\030\007 \003(\01326.google.spanner.admin.instan"
          + "ce.v1.Instance.LabelsEntry\022\025\n\rendpoint_u"
          + "ris\030\010 \003(\t\0225\n\013create_time\030\013 \001(\0132\032.google."
          + "protobuf.TimestampB\004\342A\001\003\0225\n\013update_time\030"
          + "\014 \001(\0132\032.google.protobuf.TimestampB\004\342A\001\003\022"
          + "O\n\022autoscaling_config\030\021 \001(\01323.google.spa"
          + "nner.admin.instance.v1.AutoscalingConfig"
          + "\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 "
          + "\001(\t:\0028\001\"7\n\005State\022\025\n\021STATE_UNSPECIFIED\020\000\022"
          + "\014\n\010CREATING\020\001\022\t\n\005READY\020\002:M\352AJ\n\037spanner.g"
          + "oogleapis.com/Instance\022\'projects/{projec"
          + "t}/instances/{instance}\"\211\001\n\032ListInstance"
          + "ConfigsRequest\022D\n\006parent\030\001 \001(\tB4\342A\001\002\372A-\n"
          + "+cloudresourcemanager.googleapis.com/Pro"
          + "ject\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 "
          + "\001(\t\"\202\001\n\033ListInstanceConfigsResponse\022J\n\020i"
          + "nstance_configs\030\001 \003(\01320.google.spanner.a"
          + "dmin.instance.v1.InstanceConfig\022\027\n\017next_"
          + "page_token\030\002 \001(\t\"X\n\030GetInstanceConfigReq"
          + "uest\022<\n\004name\030\001 \001(\tB.\342A\001\002\372A\'\n%spanner.goo"
          + "gleapis.com/InstanceConfig\"\355\001\n\033CreateIns"
          + "tanceConfigRequest\022D\n\006parent\030\001 \001(\tB4\342A\001\002"
          + "\372A-\n+cloudresourcemanager.googleapis.com"
          + "/Project\022 \n\022instance_config_id\030\002 \001(\tB\004\342A"
          + "\001\002\022O\n\017instance_config\030\003 \001(\01320.google.spa"
          + "nner.admin.instance.v1.InstanceConfigB\004\342"
          + "A\001\002\022\025\n\rvalidate_only\030\004 \001(\010\"\274\001\n\033UpdateIns"
          + "tanceConfigRequest\022O\n\017instance_config\030\001 "
          + "\001(\01320.google.spanner.admin.instance.v1.I"
          + "nstanceConfigB\004\342A\001\002\0225\n\013update_mask\030\002 \001(\013"
          + "2\032.google.protobuf.FieldMaskB\004\342A\001\002\022\025\n\rva"
          + "lidate_only\030\003 \001(\010\"\200\001\n\033DeleteInstanceConf"
          + "igRequest\022<\n\004name\030\001 \001(\tB.\342A\001\002\372A\'\n%spanne"
          + "r.googleapis.com/InstanceConfig\022\014\n\004etag\030"
          + "\002 \001(\t\022\025\n\rvalidate_only\030\003 \001(\010\"\242\001\n#ListIns"
          + "tanceConfigOperationsRequest\022D\n\006parent\030\001"
          + " \001(\tB4\342A\001\002\372A-\n+cloudresourcemanager.goog"
          + "leapis.com/Project\022\016\n\006filter\030\002 \001(\t\022\021\n\tpa"
          + "ge_size\030\003 \001(\005\022\022\n\npage_token\030\004 \001(\t\"r\n$Lis"
          + "tInstanceConfigOperationsResponse\0221\n\nope"
          + "rations\030\001 \003(\0132\035.google.longrunning.Opera"
          + "tion\022\027\n\017next_page_token\030\002 \001(\t\"|\n\022GetInst"
          + "anceRequest\0226\n\004name\030\001 \001(\tB(\342A\001\002\372A!\n\037span"
          + "ner.googleapis.com/Instance\022.\n\nfield_mas"
          + "k\030\002 \001(\0132\032.google.protobuf.FieldMask\"\274\001\n\025"
          + "CreateInstanceRequest\022D\n\006parent\030\001 \001(\tB4\342"
          + "A\001\002\372A-\n+cloudresourcemanager.googleapis."
          + "com/Project\022\031\n\013instance_id\030\002 \001(\tB\004\342A\001\002\022B"
          + "\n\010instance\030\003 \001(\0132*.google.spanner.admin."
          + "instance.v1.InstanceB\004\342A\001\002\"\223\001\n\024ListInsta"
          + "ncesRequest\022D\n\006parent\030\001 \001(\tB4\342A\001\002\372A-\n+cl"
          + "oudresourcemanager.googleapis.com/Projec"
          + "t\022\021\n\tpage_size\030\002 \001(\005\022\022\n\npage_token\030\003 \001(\t"
          + "\022\016\n\006filter\030\004 \001(\t\"o\n\025ListInstancesRespons"
          + "e\022=\n\tinstances\030\001 \003(\0132*.google.spanner.ad"
          + "min.instance.v1.Instance\022\027\n\017next_page_to"
          + "ken\030\002 \001(\t\"\221\001\n\025UpdateInstanceRequest\022B\n\010i"
          + "nstance\030\001 \001(\0132*.google.spanner.admin.ins"
          + "tance.v1.InstanceB\004\342A\001\002\0224\n\nfield_mask\030\002 "
          + "\001(\0132\032.google.protobuf.FieldMaskB\004\342A\001\002\"O\n"
          + "\025DeleteInstanceRequest\0226\n\004name\030\001 \001(\tB(\342A"
          + "\001\002\372A!\n\037spanner.googleapis.com/Instance\"\345"
          + "\001\n\026CreateInstanceMetadata\022<\n\010instance\030\001 "
          + "\001(\0132*.google.spanner.admin.instance.v1.I"
          + "nstance\022.\n\nstart_time\030\002 \001(\0132\032.google.pro"
          + "tobuf.Timestamp\022/\n\013cancel_time\030\003 \001(\0132\032.g"
          + "oogle.protobuf.Timestamp\022,\n\010end_time\030\004 \001"
          + "(\0132\032.google.protobuf.Timestamp\"\345\001\n\026Updat"
          + "eInstanceMetadata\022<\n\010instance\030\001 \001(\0132*.go"
          + "ogle.spanner.admin.instance.v1.Instance\022"
          + ".\n\nstart_time\030\002 \001(\0132\032.google.protobuf.Ti"
          + "mestamp\022/\n\013cancel_time\030\003 \001(\0132\032.google.pr"
          + "otobuf.Timestamp\022,\n\010end_time\030\004 \001(\0132\032.goo"
          + "gle.protobuf.Timestamp\"\341\001\n\034CreateInstanc"
          + "eConfigMetadata\022I\n\017instance_config\030\001 \001(\013"
          + "20.google.spanner.admin.instance.v1.Inst"
          + "anceConfig\022E\n\010progress\030\002 \001(\01323.google.sp"
          + "anner.admin.instance.v1.OperationProgres"
          + "s\022/\n\013cancel_time\030\003 \001(\0132\032.google.protobuf"
          + ".Timestamp\"\341\001\n\034UpdateInstanceConfigMetad"
          + "ata\022I\n\017instance_config\030\001 \001(\01320.google.sp"
          + "anner.admin.instance.v1.InstanceConfig\022E"
          + "\n\010progress\030\002 \001(\01323.google.spanner.admin."
          + "instance.v1.OperationProgress\022/\n\013cancel_"
          + "time\030\003 \001(\0132\032.google.protobuf.Timestamp2\362"
          + "\030\n\rInstanceAdmin\022\314\001\n\023ListInstanceConfigs"
          + "\022<.google.spanner.admin.instance.v1.List"
          + "InstanceConfigsRequest\032=.google.spanner."
          + "admin.instance.v1.ListInstanceConfigsRes"
          + "ponse\"8\332A\006parent\202\323\344\223\002)\022\'/v1/{parent=proj"
          + "ects/*}/instanceConfigs\022\271\001\n\021GetInstanceC"
          + "onfig\022:.google.spanner.admin.instance.v1"
          + ".GetInstanceConfigRequest\0320.google.spann"
          + "er.admin.instance.v1.InstanceConfig\"6\332A\004"
          + "name\202\323\344\223\002)\022\'/v1/{name=projects/*/instanc"
          + "eConfigs/*}\022\310\002\n\024CreateInstanceConfig\022=.g"
          + "oogle.spanner.admin.instance.v1.CreateIn"
          + "stanceConfigRequest\032\035.google.longrunning"
          + ".Operation\"\321\001\312Ap\n/google.spanner.admin.i"
          + "nstance.v1.InstanceConfig\022=google.spanne"
          + "r.admin.instance.v1.CreateInstanceConfig"
          + "Metadata\332A)parent,instance_config,instan"
          + "ce_config_id\202\323\344\223\002,\"\'/v1/{parent=projects"
          + "/*}/instanceConfigs:\001*\022\312\002\n\024UpdateInstanc"
          + "eConfig\022=.google.spanner.admin.instance."
          + "v1.UpdateInstanceConfigRequest\032\035.google."
          + "longrunning.Operation\"\323\001\312Ap\n/google.span"
          + "ner.admin.instance.v1.InstanceConfig\022=go"
          + "ogle.spanner.admin.instance.v1.UpdateIns"
          + "tanceConfigMetadata\332A\033instance_config,up"
          + "date_mask\202\323\344\223\002<27/v1/{instance_config.na"
          + "me=projects/*/instanceConfigs/*}:\001*\022\245\001\n\024"
          + "DeleteInstanceConfig\022=.google.spanner.ad"
          + "min.instance.v1.DeleteInstanceConfigRequ"
          + "est\032\026.google.protobuf.Empty\"6\332A\004name\202\323\344\223"
          + "\002)*\'/v1/{name=projects/*/instanceConfigs"
          + "/*}\022\360\001\n\034ListInstanceConfigOperations\022E.g"
          + "oogle.spanner.admin.instance.v1.ListInst"
          + "anceConfigOperationsRequest\032F.google.spa"
          + "nner.admin.instance.v1.ListInstanceConfi"
          + "gOperationsResponse\"A\332A\006parent\202\323\344\223\0022\0220/v"
          + "1/{parent=projects/*}/instanceConfigOper"
          + "ations\022\264\001\n\rListInstances\0226.google.spanne"
          + "r.admin.instance.v1.ListInstancesRequest"
          + "\0327.google.spanner.admin.instance.v1.List"
          + "InstancesResponse\"2\332A\006parent\202\323\344\223\002#\022!/v1/"
          + "{parent=projects/*}/instances\022\241\001\n\013GetIns"
          + "tance\0224.google.spanner.admin.instance.v1"
          + ".GetInstanceRequest\032*.google.spanner.adm"
          + "in.instance.v1.Instance\"0\332A\004name\202\323\344\223\002#\022!"
          + "/v1/{name=projects/*/instances/*}\022\234\002\n\016Cr"
          + "eateInstance\0227.google.spanner.admin.inst"
          + "ance.v1.CreateInstanceRequest\032\035.google.l"
          + "ongrunning.Operation\"\261\001\312Ad\n)google.spann"
          + "er.admin.instance.v1.Instance\0227google.sp"
          + "anner.admin.instance.v1.CreateInstanceMe"
          + "tadata\332A\033parent,instance_id,instance\202\323\344\223"
          + "\002&\"!/v1/{parent=projects/*}/instances:\001*"
          + "\022\235\002\n\016UpdateInstance\0227.google.spanner.adm"
          + "in.instance.v1.UpdateInstanceRequest\032\035.g"
          + "oogle.longrunning.Operation\"\262\001\312Ad\n)googl"
          + "e.spanner.admin.instance.v1.Instance\0227go"
          + "ogle.spanner.admin.instance.v1.UpdateIns"
          + "tanceMetadata\332A\023instance,field_mask\202\323\344\223\002"
          + "/2*/v1/{instance.name=projects/*/instanc"
          + "es/*}:\001*\022\223\001\n\016DeleteInstance\0227.google.spa"
          + "nner.admin.instance.v1.DeleteInstanceReq"
          + "uest\032\026.google.protobuf.Empty\"0\332A\004name\202\323\344"
          + "\223\002#*!/v1/{name=projects/*/instances/*}\022\232"
          + "\001\n\014SetIamPolicy\022\".google.iam.v1.SetIamPo"
          + "licyRequest\032\025.google.iam.v1.Policy\"O\332A\017r"
          + "esource,policy\202\323\344\223\0027\"2/v1/{resource=proj"
          + "ects/*/instances/*}:setIamPolicy:\001*\022\223\001\n\014"
          + "GetIamPolicy\022\".google.iam.v1.GetIamPolic"
          + "yRequest\032\025.google.iam.v1.Policy\"H\332A\010reso"
          + "urce\202\323\344\223\0027\"2/v1/{resource=projects/*/ins"
          + "tances/*}:getIamPolicy:\001*\022\305\001\n\022TestIamPer"
          + "missions\022(.google.iam.v1.TestIamPermissi"
          + "onsRequest\032).google.iam.v1.TestIamPermis"
          + "sionsResponse\"Z\332A\024resource,permissions\202\323"
          + "\344\223\002=\"8/v1/{resource=projects/*/instances"
          + "/*}:testIamPermissions:\001*\032x\312A\026spanner.go"
          + "ogleapis.com\322A\\https://www.googleapis.co"
          + "m/auth/cloud-platform,https://www.google"
          + "apis.com/auth/spanner.adminB\213\002\n$com.goog"
          + "le.spanner.admin.instance.v1B\031SpannerIns"
          + "tanceAdminProtoP\001ZFcloud.google.com/go/s"
          + "panner/admin/instance/apiv1/instancepb;i"
          + "nstancepb\252\002&Google.Cloud.Spanner.Admin.I"
          + "nstance.V1\312\002&Google\\Cloud\\Spanner\\Admin\\"
          + "Instance\\V1\352\002+Google::Cloud::Spanner::Ad"
          + "min::Instance::V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.iam.v1.IamPolicyProto.getDescriptor(),
              com.google.iam.v1.PolicyProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.EmptyProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.spanner.admin.instance.v1.CommonProto.getDescriptor(),
            });
    internal_static_google_spanner_admin_instance_v1_ReplicaInfo_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_spanner_admin_instance_v1_ReplicaInfo_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_ReplicaInfo_descriptor,
            new java.lang.String[] {
              "Location", "Type", "DefaultLeaderLocation",
            });
    internal_static_google_spanner_admin_instance_v1_InstanceConfig_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_spanner_admin_instance_v1_InstanceConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_InstanceConfig_descriptor,
            new java.lang.String[] {
              "Name",
              "DisplayName",
              "ConfigType",
              "Replicas",
              "OptionalReplicas",
              "BaseConfig",
              "Labels",
              "Etag",
              "LeaderOptions",
              "Reconciling",
              "State",
            });
    internal_static_google_spanner_admin_instance_v1_InstanceConfig_LabelsEntry_descriptor =
        internal_static_google_spanner_admin_instance_v1_InstanceConfig_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_spanner_admin_instance_v1_InstanceConfig_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_InstanceConfig_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_descriptor,
            new java.lang.String[] {
              "AutoscalingLimits", "AutoscalingTargets",
            });
    internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_AutoscalingLimits_descriptor =
        internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_AutoscalingLimits_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_AutoscalingLimits_descriptor,
            new java.lang.String[] {
              "MinNodes",
              "MinProcessingUnits",
              "MaxNodes",
              "MaxProcessingUnits",
              "MinLimit",
              "MaxLimit",
            });
    internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_AutoscalingTargets_descriptor =
        internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_AutoscalingTargets_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_AutoscalingConfig_AutoscalingTargets_descriptor,
            new java.lang.String[] {
              "HighPriorityCpuUtilizationPercent", "StorageUtilizationPercent",
            });
    internal_static_google_spanner_admin_instance_v1_Instance_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_spanner_admin_instance_v1_Instance_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_Instance_descriptor,
            new java.lang.String[] {
              "Name",
              "Config",
              "DisplayName",
              "NodeCount",
              "ProcessingUnits",
              "State",
              "Labels",
              "EndpointUris",
              "CreateTime",
              "UpdateTime",
              "AutoscalingConfig",
            });
    internal_static_google_spanner_admin_instance_v1_Instance_LabelsEntry_descriptor =
        internal_static_google_spanner_admin_instance_v1_Instance_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_spanner_admin_instance_v1_Instance_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_Instance_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_spanner_admin_instance_v1_ListInstanceConfigsRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_spanner_admin_instance_v1_ListInstanceConfigsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_ListInstanceConfigsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken",
            });
    internal_static_google_spanner_admin_instance_v1_ListInstanceConfigsResponse_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_spanner_admin_instance_v1_ListInstanceConfigsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_ListInstanceConfigsResponse_descriptor,
            new java.lang.String[] {
              "InstanceConfigs", "NextPageToken",
            });
    internal_static_google_spanner_admin_instance_v1_GetInstanceConfigRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_spanner_admin_instance_v1_GetInstanceConfigRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_GetInstanceConfigRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_spanner_admin_instance_v1_CreateInstanceConfigRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_spanner_admin_instance_v1_CreateInstanceConfigRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_CreateInstanceConfigRequest_descriptor,
            new java.lang.String[] {
              "Parent", "InstanceConfigId", "InstanceConfig", "ValidateOnly",
            });
    internal_static_google_spanner_admin_instance_v1_UpdateInstanceConfigRequest_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_spanner_admin_instance_v1_UpdateInstanceConfigRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_UpdateInstanceConfigRequest_descriptor,
            new java.lang.String[] {
              "InstanceConfig", "UpdateMask", "ValidateOnly",
            });
    internal_static_google_spanner_admin_instance_v1_DeleteInstanceConfigRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_spanner_admin_instance_v1_DeleteInstanceConfigRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_DeleteInstanceConfigRequest_descriptor,
            new java.lang.String[] {
              "Name", "Etag", "ValidateOnly",
            });
    internal_static_google_spanner_admin_instance_v1_ListInstanceConfigOperationsRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_spanner_admin_instance_v1_ListInstanceConfigOperationsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_ListInstanceConfigOperationsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "Filter", "PageSize", "PageToken",
            });
    internal_static_google_spanner_admin_instance_v1_ListInstanceConfigOperationsResponse_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_spanner_admin_instance_v1_ListInstanceConfigOperationsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_ListInstanceConfigOperationsResponse_descriptor,
            new java.lang.String[] {
              "Operations", "NextPageToken",
            });
    internal_static_google_spanner_admin_instance_v1_GetInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_spanner_admin_instance_v1_GetInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_GetInstanceRequest_descriptor,
            new java.lang.String[] {
              "Name", "FieldMask",
            });
    internal_static_google_spanner_admin_instance_v1_CreateInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_spanner_admin_instance_v1_CreateInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_CreateInstanceRequest_descriptor,
            new java.lang.String[] {
              "Parent", "InstanceId", "Instance",
            });
    internal_static_google_spanner_admin_instance_v1_ListInstancesRequest_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_spanner_admin_instance_v1_ListInstancesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_ListInstancesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "Filter",
            });
    internal_static_google_spanner_admin_instance_v1_ListInstancesResponse_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_spanner_admin_instance_v1_ListInstancesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_ListInstancesResponse_descriptor,
            new java.lang.String[] {
              "Instances", "NextPageToken",
            });
    internal_static_google_spanner_admin_instance_v1_UpdateInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_spanner_admin_instance_v1_UpdateInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_UpdateInstanceRequest_descriptor,
            new java.lang.String[] {
              "Instance", "FieldMask",
            });
    internal_static_google_spanner_admin_instance_v1_DeleteInstanceRequest_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_spanner_admin_instance_v1_DeleteInstanceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_DeleteInstanceRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_spanner_admin_instance_v1_CreateInstanceMetadata_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_spanner_admin_instance_v1_CreateInstanceMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_CreateInstanceMetadata_descriptor,
            new java.lang.String[] {
              "Instance", "StartTime", "CancelTime", "EndTime",
            });
    internal_static_google_spanner_admin_instance_v1_UpdateInstanceMetadata_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_spanner_admin_instance_v1_UpdateInstanceMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_UpdateInstanceMetadata_descriptor,
            new java.lang.String[] {
              "Instance", "StartTime", "CancelTime", "EndTime",
            });
    internal_static_google_spanner_admin_instance_v1_CreateInstanceConfigMetadata_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_spanner_admin_instance_v1_CreateInstanceConfigMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_CreateInstanceConfigMetadata_descriptor,
            new java.lang.String[] {
              "InstanceConfig", "Progress", "CancelTime",
            });
    internal_static_google_spanner_admin_instance_v1_UpdateInstanceConfigMetadata_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_spanner_admin_instance_v1_UpdateInstanceConfigMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_spanner_admin_instance_v1_UpdateInstanceConfigMetadata_descriptor,
            new java.lang.String[] {
              "InstanceConfig", "Progress", "CancelTime",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.iam.v1.IamPolicyProto.getDescriptor();
    com.google.iam.v1.PolicyProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.spanner.admin.instance.v1.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
