/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/admin/database/v1/backup.proto

package com.google.spanner.admin.database.v1;

/** Protobuf type {@code google.spanner.admin.database.v1.BackupSchedule} */
public final class BackupSchedule extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.spanner.admin.database.v1.BackupSchedule)
    BackupScheduleOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use BackupSchedule.newBuilder() to construct.
  private BackupSchedule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private BackupSchedule() {
    name_ = "";
    creationSpecCron_ = "";
    retentionDuration_ = "";
    optionalDummyField_ = "";
    requiredDummyField_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new BackupSchedule();
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.spanner.admin.database.v1.BackupProto
        .internal_static_google_spanner_admin_database_v1_BackupSchedule_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.spanner.admin.database.v1.BackupProto
        .internal_static_google_spanner_admin_database_v1_BackupSchedule_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.spanner.admin.database.v1.BackupSchedule.class,
            com.google.spanner.admin.database.v1.BackupSchedule.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;

  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   *
   *
   * <pre>
   * Required. The name of the backup schedule.
   * </pre>
   *
   * <code>string name = 1;</code>
   *
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Required. The name of the backup schedule.
   * </pre>
   *
   * <code>string name = 1;</code>
   *
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATION_SPEC_CRON_FIELD_NUMBER = 2;

  @SuppressWarnings("serial")
  private volatile java.lang.Object creationSpecCron_ = "";
  /**
   *
   *
   * <pre>
   * Required. Crontab text representation for how often
   * backups are created for this schedule.
   * </pre>
   *
   * <code>string creation_spec_cron = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The creationSpecCron.
   */
  @java.lang.Override
  public java.lang.String getCreationSpecCron() {
    java.lang.Object ref = creationSpecCron_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creationSpecCron_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Required. Crontab text representation for how often
   * backups are created for this schedule.
   * </pre>
   *
   * <code>string creation_spec_cron = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The bytes for creationSpecCron.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCreationSpecCronBytes() {
    java.lang.Object ref = creationSpecCron_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      creationSpecCron_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RETENTION_DURATION_FIELD_NUMBER = 3;

  @SuppressWarnings("serial")
  private volatile java.lang.Object retentionDuration_ = "";
  /**
   *
   *
   * <pre>
   * Required. How long to keep each backup [1d-365d].
   * </pre>
   *
   * <code>string retention_duration = 3;</code>
   *
   * @return The retentionDuration.
   */
  @java.lang.Override
  public java.lang.String getRetentionDuration() {
    java.lang.Object ref = retentionDuration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      retentionDuration_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Required. How long to keep each backup [1d-365d].
   * </pre>
   *
   * <code>string retention_duration = 3;</code>
   *
   * @return The bytes for retentionDuration.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRetentionDurationBytes() {
    java.lang.Object ref = retentionDuration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      retentionDuration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENCRYPTION_CONFIG_FIELD_NUMBER = 4;
  private com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig
      encryptionConfig_;
  /**
   *
   *
   * <pre>
   * An encryption info describing the encryption type and key resources
   * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
   * </pre>
   *
   * <code>
   * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   *
   * @return Whether the encryptionConfig field is set.
   */
  @java.lang.Override
  public boolean hasEncryptionConfig() {
    return encryptionConfig_ != null;
  }
  /**
   *
   *
   * <pre>
   * An encryption info describing the encryption type and key resources
   * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
   * </pre>
   *
   * <code>
   * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   *
   * @return The encryptionConfig.
   */
  @java.lang.Override
  public com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig
      getEncryptionConfig() {
    return encryptionConfig_ == null
        ? com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig
            .getDefaultInstance()
        : encryptionConfig_;
  }
  /**
   *
   *
   * <pre>
   * An encryption info describing the encryption type and key resources
   * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
   * </pre>
   *
   * <code>
   * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  @java.lang.Override
  public com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfigOrBuilder
      getEncryptionConfigOrBuilder() {
    return encryptionConfig_ == null
        ? com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig
            .getDefaultInstance()
        : encryptionConfig_;
  }

  public static final int OPTIONAL_DUMMY_FIELD_FIELD_NUMBER = 5;

  @SuppressWarnings("serial")
  private volatile java.lang.Object optionalDummyField_ = "";
  /**
   * <code>string optional_dummy_field = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The optionalDummyField.
   */
  @java.lang.Override
  public java.lang.String getOptionalDummyField() {
    java.lang.Object ref = optionalDummyField_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      optionalDummyField_ = s;
      return s;
    }
  }
  /**
   * <code>string optional_dummy_field = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
   *
   * @return The bytes for optionalDummyField.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getOptionalDummyFieldBytes() {
    java.lang.Object ref = optionalDummyField_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      optionalDummyField_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUIRED_DUMMY_FIELD_FIELD_NUMBER = 6;

  @SuppressWarnings("serial")
  private volatile java.lang.Object requiredDummyField_ = "";
  /**
   * <code>string required_dummy_field = 6 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The requiredDummyField.
   */
  @java.lang.Override
  public java.lang.String getRequiredDummyField() {
    java.lang.Object ref = requiredDummyField_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requiredDummyField_ = s;
      return s;
    }
  }
  /**
   * <code>string required_dummy_field = 6 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The bytes for requiredDummyField.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRequiredDummyFieldBytes() {
    java.lang.Object ref = requiredDummyField_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      requiredDummyField_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creationSpecCron_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, creationSpecCron_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(retentionDuration_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, retentionDuration_);
    }
    if (encryptionConfig_ != null) {
      output.writeMessage(4, getEncryptionConfig());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(optionalDummyField_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, optionalDummyField_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requiredDummyField_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, requiredDummyField_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(creationSpecCron_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, creationSpecCron_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(retentionDuration_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, retentionDuration_);
    }
    if (encryptionConfig_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, getEncryptionConfig());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(optionalDummyField_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, optionalDummyField_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(requiredDummyField_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, requiredDummyField_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.spanner.admin.database.v1.BackupSchedule)) {
      return super.equals(obj);
    }
    com.google.spanner.admin.database.v1.BackupSchedule other =
        (com.google.spanner.admin.database.v1.BackupSchedule) obj;

    if (!getName().equals(other.getName())) return false;
    if (!getCreationSpecCron().equals(other.getCreationSpecCron())) return false;
    if (!getRetentionDuration().equals(other.getRetentionDuration())) return false;
    if (hasEncryptionConfig() != other.hasEncryptionConfig()) return false;
    if (hasEncryptionConfig()) {
      if (!getEncryptionConfig().equals(other.getEncryptionConfig())) return false;
    }
    if (!getOptionalDummyField().equals(other.getOptionalDummyField())) return false;
    if (!getRequiredDummyField().equals(other.getRequiredDummyField())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + CREATION_SPEC_CRON_FIELD_NUMBER;
    hash = (53 * hash) + getCreationSpecCron().hashCode();
    hash = (37 * hash) + RETENTION_DURATION_FIELD_NUMBER;
    hash = (53 * hash) + getRetentionDuration().hashCode();
    if (hasEncryptionConfig()) {
      hash = (37 * hash) + ENCRYPTION_CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptionConfig().hashCode();
    }
    hash = (37 * hash) + OPTIONAL_DUMMY_FIELD_FIELD_NUMBER;
    hash = (53 * hash) + getOptionalDummyField().hashCode();
    hash = (37 * hash) + REQUIRED_DUMMY_FIELD_FIELD_NUMBER;
    hash = (53 * hash) + getRequiredDummyField().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.spanner.admin.database.v1.BackupSchedule prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code google.spanner.admin.database.v1.BackupSchedule} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.spanner.admin.database.v1.BackupSchedule)
      com.google.spanner.admin.database.v1.BackupScheduleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.spanner.admin.database.v1.BackupProto
          .internal_static_google_spanner_admin_database_v1_BackupSchedule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.spanner.admin.database.v1.BackupProto
          .internal_static_google_spanner_admin_database_v1_BackupSchedule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.spanner.admin.database.v1.BackupSchedule.class,
              com.google.spanner.admin.database.v1.BackupSchedule.Builder.class);
    }

    // Construct using com.google.spanner.admin.database.v1.BackupSchedule.newBuilder()
    private Builder() {}

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      creationSpecCron_ = "";
      retentionDuration_ = "";
      encryptionConfig_ = null;
      if (encryptionConfigBuilder_ != null) {
        encryptionConfigBuilder_.dispose();
        encryptionConfigBuilder_ = null;
      }
      optionalDummyField_ = "";
      requiredDummyField_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.spanner.admin.database.v1.BackupProto
          .internal_static_google_spanner_admin_database_v1_BackupSchedule_descriptor;
    }

    @java.lang.Override
    public com.google.spanner.admin.database.v1.BackupSchedule getDefaultInstanceForType() {
      return com.google.spanner.admin.database.v1.BackupSchedule.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.spanner.admin.database.v1.BackupSchedule build() {
      com.google.spanner.admin.database.v1.BackupSchedule result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.spanner.admin.database.v1.BackupSchedule buildPartial() {
      com.google.spanner.admin.database.v1.BackupSchedule result =
          new com.google.spanner.admin.database.v1.BackupSchedule(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.spanner.admin.database.v1.BackupSchedule result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.creationSpecCron_ = creationSpecCron_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.retentionDuration_ = retentionDuration_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.encryptionConfig_ =
            encryptionConfigBuilder_ == null ? encryptionConfig_ : encryptionConfigBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.optionalDummyField_ = optionalDummyField_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.requiredDummyField_ = requiredDummyField_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.spanner.admin.database.v1.BackupSchedule) {
        return mergeFrom((com.google.spanner.admin.database.v1.BackupSchedule) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.spanner.admin.database.v1.BackupSchedule other) {
      if (other == com.google.spanner.admin.database.v1.BackupSchedule.getDefaultInstance())
        return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getCreationSpecCron().isEmpty()) {
        creationSpecCron_ = other.creationSpecCron_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getRetentionDuration().isEmpty()) {
        retentionDuration_ = other.retentionDuration_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasEncryptionConfig()) {
        mergeEncryptionConfig(other.getEncryptionConfig());
      }
      if (!other.getOptionalDummyField().isEmpty()) {
        optionalDummyField_ = other.optionalDummyField_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getRequiredDummyField().isEmpty()) {
        requiredDummyField_ = other.requiredDummyField_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 18:
              {
                creationSpecCron_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
            case 26:
              {
                retentionDuration_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
            case 34:
              {
                input.readMessage(
                    getEncryptionConfigFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
            case 42:
              {
                optionalDummyField_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
            case 50:
              {
                requiredDummyField_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     *
     *
     * <pre>
     * Required. The name of the backup schedule.
     * </pre>
     *
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. The name of the backup schedule.
     * </pre>
     *
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. The name of the backup schedule.
     * </pre>
     *
     * <code>string name = 1;</code>
     *
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. The name of the backup schedule.
     * </pre>
     *
     * <code>string name = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. The name of the backup schedule.
     * </pre>
     *
     * <code>string name = 1;</code>
     *
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object creationSpecCron_ = "";
    /**
     *
     *
     * <pre>
     * Required. Crontab text representation for how often
     * backups are created for this schedule.
     * </pre>
     *
     * <code>string creation_spec_cron = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @return The creationSpecCron.
     */
    public java.lang.String getCreationSpecCron() {
      java.lang.Object ref = creationSpecCron_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creationSpecCron_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. Crontab text representation for how often
     * backups are created for this schedule.
     * </pre>
     *
     * <code>string creation_spec_cron = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @return The bytes for creationSpecCron.
     */
    public com.google.protobuf.ByteString getCreationSpecCronBytes() {
      java.lang.Object ref = creationSpecCron_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        creationSpecCron_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. Crontab text representation for how often
     * backups are created for this schedule.
     * </pre>
     *
     * <code>string creation_spec_cron = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @param value The creationSpecCron to set.
     * @return This builder for chaining.
     */
    public Builder setCreationSpecCron(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      creationSpecCron_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. Crontab text representation for how often
     * backups are created for this schedule.
     * </pre>
     *
     * <code>string creation_spec_cron = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearCreationSpecCron() {
      creationSpecCron_ = getDefaultInstance().getCreationSpecCron();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. Crontab text representation for how often
     * backups are created for this schedule.
     * </pre>
     *
     * <code>string creation_spec_cron = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @param value The bytes for creationSpecCron to set.
     * @return This builder for chaining.
     */
    public Builder setCreationSpecCronBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      creationSpecCron_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object retentionDuration_ = "";
    /**
     *
     *
     * <pre>
     * Required. How long to keep each backup [1d-365d].
     * </pre>
     *
     * <code>string retention_duration = 3;</code>
     *
     * @return The retentionDuration.
     */
    public java.lang.String getRetentionDuration() {
      java.lang.Object ref = retentionDuration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        retentionDuration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. How long to keep each backup [1d-365d].
     * </pre>
     *
     * <code>string retention_duration = 3;</code>
     *
     * @return The bytes for retentionDuration.
     */
    public com.google.protobuf.ByteString getRetentionDurationBytes() {
      java.lang.Object ref = retentionDuration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        retentionDuration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. How long to keep each backup [1d-365d].
     * </pre>
     *
     * <code>string retention_duration = 3;</code>
     *
     * @param value The retentionDuration to set.
     * @return This builder for chaining.
     */
    public Builder setRetentionDuration(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      retentionDuration_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. How long to keep each backup [1d-365d].
     * </pre>
     *
     * <code>string retention_duration = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearRetentionDuration() {
      retentionDuration_ = getDefaultInstance().getRetentionDuration();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. How long to keep each backup [1d-365d].
     * </pre>
     *
     * <code>string retention_duration = 3;</code>
     *
     * @param value The bytes for retentionDuration to set.
     * @return This builder for chaining.
     */
    public Builder setRetentionDurationBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      retentionDuration_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig
        encryptionConfig_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig,
            com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig.Builder,
            com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfigOrBuilder>
        encryptionConfigBuilder_;
    /**
     *
     *
     * <pre>
     * An encryption info describing the encryption type and key resources
     * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
     * </pre>
     *
     * <code>
     * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
     * </code>
     *
     * @return Whether the encryptionConfig field is set.
     */
    public boolean hasEncryptionConfig() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     *
     *
     * <pre>
     * An encryption info describing the encryption type and key resources
     * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
     * </pre>
     *
     * <code>
     * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
     * </code>
     *
     * @return The encryptionConfig.
     */
    public com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig
        getEncryptionConfig() {
      if (encryptionConfigBuilder_ == null) {
        return encryptionConfig_ == null
            ? com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig
                .getDefaultInstance()
            : encryptionConfig_;
      } else {
        return encryptionConfigBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * An encryption info describing the encryption type and key resources
     * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
     * </pre>
     *
     * <code>
     * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
     * </code>
     */
    public Builder setEncryptionConfig(
        com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig value) {
      if (encryptionConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        encryptionConfig_ = value;
      } else {
        encryptionConfigBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * An encryption info describing the encryption type and key resources
     * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
     * </pre>
     *
     * <code>
     * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
     * </code>
     */
    public Builder setEncryptionConfig(
        com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig.Builder
            builderForValue) {
      if (encryptionConfigBuilder_ == null) {
        encryptionConfig_ = builderForValue.build();
      } else {
        encryptionConfigBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * An encryption info describing the encryption type and key resources
     * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
     * </pre>
     *
     * <code>
     * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
     * </code>
     */
    public Builder mergeEncryptionConfig(
        com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig value) {
      if (encryptionConfigBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)
            && encryptionConfig_ != null
            && encryptionConfig_
                != com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig
                    .getDefaultInstance()) {
          getEncryptionConfigBuilder().mergeFrom(value);
        } else {
          encryptionConfig_ = value;
        }
      } else {
        encryptionConfigBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * An encryption info describing the encryption type and key resources
     * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
     * </pre>
     *
     * <code>
     * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
     * </code>
     */
    public Builder clearEncryptionConfig() {
      bitField0_ = (bitField0_ & ~0x00000008);
      encryptionConfig_ = null;
      if (encryptionConfigBuilder_ != null) {
        encryptionConfigBuilder_.dispose();
        encryptionConfigBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * An encryption info describing the encryption type and key resources
     * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
     * </pre>
     *
     * <code>
     * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
     * </code>
     */
    public com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig.Builder
        getEncryptionConfigBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getEncryptionConfigFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * An encryption info describing the encryption type and key resources
     * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
     * </pre>
     *
     * <code>
     * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
     * </code>
     */
    public com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfigOrBuilder
        getEncryptionConfigOrBuilder() {
      if (encryptionConfigBuilder_ != null) {
        return encryptionConfigBuilder_.getMessageOrBuilder();
      } else {
        return encryptionConfig_ == null
            ? com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig
                .getDefaultInstance()
            : encryptionConfig_;
      }
    }
    /**
     *
     *
     * <pre>
     * An encryption info describing the encryption type and key resources
     * in Cloud KMS used to encrypt/decrypt the backup created by this schedule.
     * </pre>
     *
     * <code>
     * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig encryption_config = 4 [(.google.api.field_behavior) = OPTIONAL];
     * </code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig,
            com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig.Builder,
            com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfigOrBuilder>
        getEncryptionConfigFieldBuilder() {
      if (encryptionConfigBuilder_ == null) {
        encryptionConfigBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig,
                com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig.Builder,
                com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfigOrBuilder>(
                getEncryptionConfig(), getParentForChildren(), isClean());
        encryptionConfig_ = null;
      }
      return encryptionConfigBuilder_;
    }

    private java.lang.Object optionalDummyField_ = "";
    /**
     * <code>string optional_dummy_field = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
     *
     * @return The optionalDummyField.
     */
    public java.lang.String getOptionalDummyField() {
      java.lang.Object ref = optionalDummyField_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        optionalDummyField_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string optional_dummy_field = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
     *
     * @return The bytes for optionalDummyField.
     */
    public com.google.protobuf.ByteString getOptionalDummyFieldBytes() {
      java.lang.Object ref = optionalDummyField_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        optionalDummyField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string optional_dummy_field = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
     *
     * @param value The optionalDummyField to set.
     * @return This builder for chaining.
     */
    public Builder setOptionalDummyField(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      optionalDummyField_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string optional_dummy_field = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearOptionalDummyField() {
      optionalDummyField_ = getDefaultInstance().getOptionalDummyField();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string optional_dummy_field = 5 [(.google.api.field_behavior) = OPTIONAL];</code>
     *
     * @param value The bytes for optionalDummyField to set.
     * @return This builder for chaining.
     */
    public Builder setOptionalDummyFieldBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      optionalDummyField_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object requiredDummyField_ = "";
    /**
     * <code>string required_dummy_field = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @return The requiredDummyField.
     */
    public java.lang.String getRequiredDummyField() {
      java.lang.Object ref = requiredDummyField_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requiredDummyField_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string required_dummy_field = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @return The bytes for requiredDummyField.
     */
    public com.google.protobuf.ByteString getRequiredDummyFieldBytes() {
      java.lang.Object ref = requiredDummyField_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        requiredDummyField_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string required_dummy_field = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @param value The requiredDummyField to set.
     * @return This builder for chaining.
     */
    public Builder setRequiredDummyField(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      requiredDummyField_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string required_dummy_field = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearRequiredDummyField() {
      requiredDummyField_ = getDefaultInstance().getRequiredDummyField();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string required_dummy_field = 6 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @param value The bytes for requiredDummyField to set.
     * @return This builder for chaining.
     */
    public Builder setRequiredDummyFieldBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      requiredDummyField_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.spanner.admin.database.v1.BackupSchedule)
  }

  // @@protoc_insertion_point(class_scope:google.spanner.admin.database.v1.BackupSchedule)
  private static final com.google.spanner.admin.database.v1.BackupSchedule DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.spanner.admin.database.v1.BackupSchedule();
  }

  public static com.google.spanner.admin.database.v1.BackupSchedule getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BackupSchedule> PARSER =
      new com.google.protobuf.AbstractParser<BackupSchedule>() {
        @java.lang.Override
        public BackupSchedule parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<BackupSchedule> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BackupSchedule> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.spanner.admin.database.v1.BackupSchedule getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
