/*
 * Copyright 2023 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/spanner/admin/database/v1/backup.proto

package com.google.spanner.admin.database.v1;

public interface CreateBackupScheduleEncryptionConfigOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The encryption type of the backup.
   * </pre>
   *
   * <code>
   * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig.EncryptionType encryption_type = 1;
   * </code>
   *
   * @return The enum numeric value on the wire for encryptionType.
   */
  int getEncryptionTypeValue();
  /**
   *
   *
   * <pre>
   * The encryption type of the backup.
   * </pre>
   *
   * <code>
   * .google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig.EncryptionType encryption_type = 1;
   * </code>
   *
   * @return The encryptionType.
   */
  com.google.spanner.admin.database.v1.CreateBackupScheduleEncryptionConfig.EncryptionType
      getEncryptionType();

  /**
   *
   *
   * <pre>
   * The Cloud KMS Keys that will be used to protect the backup.
   * This field should be set only when
   * [encryption_type][CreateBackupScheduleEncryptionConfig.encryption_type] is
   * `CUSTOMER_MANAGED_ENCRYPTION`.
   * Values are of the form:   `projects/&lt;project&gt;/locations/&lt;location&gt;/keyRings/&lt;key_ring&gt;/cryptoKeys/&lt;kms_key_name&gt;`.
   * There can be multiple keys pertaining to CMMR. Link
   * </pre>
   *
   * <code>repeated string kms_key_names = 2;</code>
   *
   * @return A list containing the kmsKeyNames.
   */
  java.util.List<java.lang.String> getKmsKeyNamesList();
  /**
   *
   *
   * <pre>
   * The Cloud KMS Keys that will be used to protect the backup.
   * This field should be set only when
   * [encryption_type][CreateBackupScheduleEncryptionConfig.encryption_type] is
   * `CUSTOMER_MANAGED_ENCRYPTION`.
   * Values are of the form:   `projects/&lt;project&gt;/locations/&lt;location&gt;/keyRings/&lt;key_ring&gt;/cryptoKeys/&lt;kms_key_name&gt;`.
   * There can be multiple keys pertaining to CMMR. Link
   * </pre>
   *
   * <code>repeated string kms_key_names = 2;</code>
   *
   * @return The count of kmsKeyNames.
   */
  int getKmsKeyNamesCount();
  /**
   *
   *
   * <pre>
   * The Cloud KMS Keys that will be used to protect the backup.
   * This field should be set only when
   * [encryption_type][CreateBackupScheduleEncryptionConfig.encryption_type] is
   * `CUSTOMER_MANAGED_ENCRYPTION`.
   * Values are of the form:   `projects/&lt;project&gt;/locations/&lt;location&gt;/keyRings/&lt;key_ring&gt;/cryptoKeys/&lt;kms_key_name&gt;`.
   * There can be multiple keys pertaining to CMMR. Link
   * </pre>
   *
   * <code>repeated string kms_key_names = 2;</code>
   *
   * @param index The index of the element to return.
   * @return The kmsKeyNames at the given index.
   */
  java.lang.String getKmsKeyNames(int index);
  /**
   *
   *
   * <pre>
   * The Cloud KMS Keys that will be used to protect the backup.
   * This field should be set only when
   * [encryption_type][CreateBackupScheduleEncryptionConfig.encryption_type] is
   * `CUSTOMER_MANAGED_ENCRYPTION`.
   * Values are of the form:   `projects/&lt;project&gt;/locations/&lt;location&gt;/keyRings/&lt;key_ring&gt;/cryptoKeys/&lt;kms_key_name&gt;`.
   * There can be multiple keys pertaining to CMMR. Link
   * </pre>
   *
   * <code>repeated string kms_key_names = 2;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the kmsKeyNames at the given index.
   */
  com.google.protobuf.ByteString getKmsKeyNamesBytes(int index);
}
